/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AboutProjectRouteImport } from './routes/about-project'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FeaturesSkillGapRouteImport } from './routes/features/skill-gap'
import { Route as FeaturesRoadmapRouteImport } from './routes/features/roadmap'
import { Route as FeaturesResumeRefinerRouteImport } from './routes/features/resume-refiner'
import { Route as FeaturesResumeAnalyzerRouteImport } from './routes/features/resume-analyzer'
import { Route as FeaturesRecommendationsRouteImport } from './routes/features/recommendations'
import { Route as FeaturesPitchCoachRouteImport } from './routes/features/pitch-coach'
import { Route as FeaturesNegotiatorRouteImport } from './routes/features/negotiator'
import { Route as FeaturesInterviewPrepRouteImport } from './routes/features/interview-prep'
import { Route as FeaturesEmergingJobsRouteImport } from './routes/features/emerging-jobs'
import { Route as FeaturesBannerBuilderRouteImport } from './routes/features/banner-builder'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutProjectRoute = AboutProjectRouteImport.update({
  id: '/about-project',
  path: '/about-project',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesSkillGapRoute = FeaturesSkillGapRouteImport.update({
  id: '/features/skill-gap',
  path: '/features/skill-gap',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoadmapRoute = FeaturesRoadmapRouteImport.update({
  id: '/features/roadmap',
  path: '/features/roadmap',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesResumeRefinerRoute = FeaturesResumeRefinerRouteImport.update({
  id: '/features/resume-refiner',
  path: '/features/resume-refiner',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesResumeAnalyzerRoute = FeaturesResumeAnalyzerRouteImport.update({
  id: '/features/resume-analyzer',
  path: '/features/resume-analyzer',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRecommendationsRoute = FeaturesRecommendationsRouteImport.update({
  id: '/features/recommendations',
  path: '/features/recommendations',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesPitchCoachRoute = FeaturesPitchCoachRouteImport.update({
  id: '/features/pitch-coach',
  path: '/features/pitch-coach',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesNegotiatorRoute = FeaturesNegotiatorRouteImport.update({
  id: '/features/negotiator',
  path: '/features/negotiator',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesInterviewPrepRoute = FeaturesInterviewPrepRouteImport.update({
  id: '/features/interview-prep',
  path: '/features/interview-prep',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesEmergingJobsRoute = FeaturesEmergingJobsRouteImport.update({
  id: '/features/emerging-jobs',
  path: '/features/emerging-jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesBannerBuilderRoute = FeaturesBannerBuilderRouteImport.update({
  id: '/features/banner-builder',
  path: '/features/banner-builder',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about-project': typeof AboutProjectRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/features/banner-builder': typeof FeaturesBannerBuilderRoute
  '/features/emerging-jobs': typeof FeaturesEmergingJobsRoute
  '/features/interview-prep': typeof FeaturesInterviewPrepRoute
  '/features/negotiator': typeof FeaturesNegotiatorRoute
  '/features/pitch-coach': typeof FeaturesPitchCoachRoute
  '/features/recommendations': typeof FeaturesRecommendationsRoute
  '/features/resume-analyzer': typeof FeaturesResumeAnalyzerRoute
  '/features/resume-refiner': typeof FeaturesResumeRefinerRoute
  '/features/roadmap': typeof FeaturesRoadmapRoute
  '/features/skill-gap': typeof FeaturesSkillGapRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about-project': typeof AboutProjectRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/features/banner-builder': typeof FeaturesBannerBuilderRoute
  '/features/emerging-jobs': typeof FeaturesEmergingJobsRoute
  '/features/interview-prep': typeof FeaturesInterviewPrepRoute
  '/features/negotiator': typeof FeaturesNegotiatorRoute
  '/features/pitch-coach': typeof FeaturesPitchCoachRoute
  '/features/recommendations': typeof FeaturesRecommendationsRoute
  '/features/resume-analyzer': typeof FeaturesResumeAnalyzerRoute
  '/features/resume-refiner': typeof FeaturesResumeRefinerRoute
  '/features/roadmap': typeof FeaturesRoadmapRoute
  '/features/skill-gap': typeof FeaturesSkillGapRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about-project': typeof AboutProjectRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/features/banner-builder': typeof FeaturesBannerBuilderRoute
  '/features/emerging-jobs': typeof FeaturesEmergingJobsRoute
  '/features/interview-prep': typeof FeaturesInterviewPrepRoute
  '/features/negotiator': typeof FeaturesNegotiatorRoute
  '/features/pitch-coach': typeof FeaturesPitchCoachRoute
  '/features/recommendations': typeof FeaturesRecommendationsRoute
  '/features/resume-analyzer': typeof FeaturesResumeAnalyzerRoute
  '/features/resume-refiner': typeof FeaturesResumeRefinerRoute
  '/features/roadmap': typeof FeaturesRoadmapRoute
  '/features/skill-gap': typeof FeaturesSkillGapRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about-project'
    | '/dashboard'
    | '/login'
    | '/signup'
    | '/features/banner-builder'
    | '/features/emerging-jobs'
    | '/features/interview-prep'
    | '/features/negotiator'
    | '/features/pitch-coach'
    | '/features/recommendations'
    | '/features/resume-analyzer'
    | '/features/resume-refiner'
    | '/features/roadmap'
    | '/features/skill-gap'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about-project'
    | '/dashboard'
    | '/login'
    | '/signup'
    | '/features/banner-builder'
    | '/features/emerging-jobs'
    | '/features/interview-prep'
    | '/features/negotiator'
    | '/features/pitch-coach'
    | '/features/recommendations'
    | '/features/resume-analyzer'
    | '/features/resume-refiner'
    | '/features/roadmap'
    | '/features/skill-gap'
  id:
    | '__root__'
    | '/'
    | '/about-project'
    | '/dashboard'
    | '/login'
    | '/signup'
    | '/features/banner-builder'
    | '/features/emerging-jobs'
    | '/features/interview-prep'
    | '/features/negotiator'
    | '/features/pitch-coach'
    | '/features/recommendations'
    | '/features/resume-analyzer'
    | '/features/resume-refiner'
    | '/features/roadmap'
    | '/features/skill-gap'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutProjectRoute: typeof AboutProjectRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  FeaturesBannerBuilderRoute: typeof FeaturesBannerBuilderRoute
  FeaturesEmergingJobsRoute: typeof FeaturesEmergingJobsRoute
  FeaturesInterviewPrepRoute: typeof FeaturesInterviewPrepRoute
  FeaturesNegotiatorRoute: typeof FeaturesNegotiatorRoute
  FeaturesPitchCoachRoute: typeof FeaturesPitchCoachRoute
  FeaturesRecommendationsRoute: typeof FeaturesRecommendationsRoute
  FeaturesResumeAnalyzerRoute: typeof FeaturesResumeAnalyzerRoute
  FeaturesResumeRefinerRoute: typeof FeaturesResumeRefinerRoute
  FeaturesRoadmapRoute: typeof FeaturesRoadmapRoute
  FeaturesSkillGapRoute: typeof FeaturesSkillGapRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about-project': {
      id: '/about-project'
      path: '/about-project'
      fullPath: '/about-project'
      preLoaderRoute: typeof AboutProjectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features/skill-gap': {
      id: '/features/skill-gap'
      path: '/features/skill-gap'
      fullPath: '/features/skill-gap'
      preLoaderRoute: typeof FeaturesSkillGapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features/roadmap': {
      id: '/features/roadmap'
      path: '/features/roadmap'
      fullPath: '/features/roadmap'
      preLoaderRoute: typeof FeaturesRoadmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features/resume-refiner': {
      id: '/features/resume-refiner'
      path: '/features/resume-refiner'
      fullPath: '/features/resume-refiner'
      preLoaderRoute: typeof FeaturesResumeRefinerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features/resume-analyzer': {
      id: '/features/resume-analyzer'
      path: '/features/resume-analyzer'
      fullPath: '/features/resume-analyzer'
      preLoaderRoute: typeof FeaturesResumeAnalyzerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features/recommendations': {
      id: '/features/recommendations'
      path: '/features/recommendations'
      fullPath: '/features/recommendations'
      preLoaderRoute: typeof FeaturesRecommendationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features/pitch-coach': {
      id: '/features/pitch-coach'
      path: '/features/pitch-coach'
      fullPath: '/features/pitch-coach'
      preLoaderRoute: typeof FeaturesPitchCoachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features/negotiator': {
      id: '/features/negotiator'
      path: '/features/negotiator'
      fullPath: '/features/negotiator'
      preLoaderRoute: typeof FeaturesNegotiatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features/interview-prep': {
      id: '/features/interview-prep'
      path: '/features/interview-prep'
      fullPath: '/features/interview-prep'
      preLoaderRoute: typeof FeaturesInterviewPrepRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features/emerging-jobs': {
      id: '/features/emerging-jobs'
      path: '/features/emerging-jobs'
      fullPath: '/features/emerging-jobs'
      preLoaderRoute: typeof FeaturesEmergingJobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features/banner-builder': {
      id: '/features/banner-builder'
      path: '/features/banner-builder'
      fullPath: '/features/banner-builder'
      preLoaderRoute: typeof FeaturesBannerBuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutProjectRoute: AboutProjectRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  FeaturesBannerBuilderRoute: FeaturesBannerBuilderRoute,
  FeaturesEmergingJobsRoute: FeaturesEmergingJobsRoute,
  FeaturesInterviewPrepRoute: FeaturesInterviewPrepRoute,
  FeaturesNegotiatorRoute: FeaturesNegotiatorRoute,
  FeaturesPitchCoachRoute: FeaturesPitchCoachRoute,
  FeaturesRecommendationsRoute: FeaturesRecommendationsRoute,
  FeaturesResumeAnalyzerRoute: FeaturesResumeAnalyzerRoute,
  FeaturesResumeRefinerRoute: FeaturesResumeRefinerRoute,
  FeaturesRoadmapRoute: FeaturesRoadmapRoute,
  FeaturesSkillGapRoute: FeaturesSkillGapRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
